// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDAp01SIsWiWIZp_IKzIvlsJBzJr6UGM',
    appId: '1:494383898132:android:51f3c6e256cfe767041101',
    messagingSenderId: '494383898132',
    projectId: 'word-4bb3c',
    storageBucket: 'word-4bb3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa03jlN0Ho8yVto1IfayfXgl9JeYOTOXs',
    appId: '1:494383898132:ios:a050ec88538e7e9a041101',
    messagingSenderId: '494383898132',
    projectId: 'word-4bb3c',
    storageBucket: 'word-4bb3c.appspot.com',
    iosClientId: '494383898132-2tjkkhin82cfj4i1c36uv7rbbi8srrls.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldofword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa03jlN0Ho8yVto1IfayfXgl9JeYOTOXs',
    appId: '1:494383898132:ios:a050ec88538e7e9a041101',
    messagingSenderId: '494383898132',
    projectId: 'word-4bb3c',
    storageBucket: 'word-4bb3c.appspot.com',
    iosClientId: '494383898132-2tjkkhin82cfj4i1c36uv7rbbi8srrls.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldofword',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPWhUJJkVJJnREH3k6CRGa8JXn8q8VcKE',
    appId: '1:494383898132:web:e67c671199856308041101',
    messagingSenderId: '494383898132',
    projectId: 'word-4bb3c',
    authDomain: 'word-4bb3c.firebaseapp.com',
    storageBucket: 'word-4bb3c.appspot.com',
    measurementId: 'G-6Y2K32HLKH',
  );
}
